# Default initial positions for cygnus's ros2_control fake system

initial_positions:
  Joint_Flipper_Back_Left: 0
  Joint_Flipper_Back_Right: 0
  Joint_Flipper_Front_Left: 0
  Joint_Flipper_Front_Right: 0