# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - group_flipper_front_left_controller
    - group_flipper_front_right_controller
    - group_flipper_back_left_controller
    - group_flipper_back_right_controller

  group_flipper_front_left_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - Joint_Flipper_Front_Left
  group_flipper_front_right_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - Joint_Flipper_Front_Right
  group_flipper_back_left_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - Joint_Flipper_Back_Left
  group_flipper_back_right_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - Joint_Flipper_Back_Right
