# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - flipper_joint_controller

  flipper_joint_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - Joint_Flipper_Back_Left
      - Joint_Flipper_Back_Right
      - Joint_Flipper_Front_Left
      - Joint_Flipper_Front_Right