# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    flipper_joint_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

flipper_joint_controller:
  ros__parameters:
    joints:
      - Joint_Flipper_Back_Left
      - Joint_Flipper_Back_Right
      - Joint_Flipper_Front_Left
      - Joint_Flipper_Front_Right
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity