# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - flipper_controller

  flipper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_flipper_arm_back_left
      - joint_flipper_arm_back_right
      - joint_flipper_arm_front_left
      - joint_flipper_arm_front_right